### PR TITLE
Created and implemented the requested /club-list subcommand...

### LINKED ISSUE #174: /club list
Add a subcommand to `/club` called `/club list` which takes in one of the club roles and displays everyone that has it, if the user has permission to give the role out.

### PR DESCRIPTION
**Pull request by MrAlLind**
...to list all users that have a given role.

Also changed the main handler to only require the user parameter for the subcommands that actually use said parameter.

Fixes #174

### CODE REVIEW

**Comment by Benjaneb** [comment]
It would be better to display them nicer, on separate rows instead of comma separated. Also, you could @ the users so you can click on them and see their profile picture. Since the response is ephemeral (only visible to you) it wont actually ping the users.

**Review by Benjaneb — CHANGES_REQUESTED** [review]
Fix above before merge

**Comment by MrAlLind** [comment]
> Fix above before merge

This has already been fixed, see the 2 commits after your first comment

**Review by Benjaneb — APPROVED** [review]
Sorry, only saw the newline fix, so I thought it still displayed only tags. :laughing: 

Looks good! Thanks a lot for the help!

**Pull request merged**
